trigger:
  - master
pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      ref: main
      name: TestTast/TaskTest

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'build'
#
#stages:
#  - stage: build
#    displayName: Build
#
#    jobs:
#      - job: gradle_build_deploy
#        displayName: 'Maven Build/Deploy'
#
#        steps:
#          - template: /build/gradle-build.yaml@templates
#
#          - template: build/deploy-spring-apps.yaml@templates
#            parameters:
#              appName: 'payment-service'